agent:
  _target_: agents.drm_mw.DrMAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  dormant_threshold: 0.025
  target_dormant_ratio: 0.2
  target_lambda: 0.5
  dormant_temp: 10
  dormant_perturb_interval: 100000
  min_perturb_factor: 0.2
  max_perturb_factor: 0.95
  perturb_rate: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_type: awake
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  expectile: 0.9
